<!-- # Chap 1 -->

<!-- # Chap 2 -->

<!-- # Chap 3 -->

<!-- # Chap 4 -->

<!-- # Chap 5 -->

<!-- # Chap 6 -->

<!-- # Chap 7 -->

<!-- # Chap 8 -->

<!-- # Chap 9 -->

<!-- # Chap 10 -->

<!-- # Chap 11 -->

<!-- # Chap 12 -->

<!-- # Chap 13 -->

<!-- # Chap 14 -->

<!-- # Chap 15 -->

<!-- # Chap 16 -->

<!-- # Chap 17 -->

<!-- # Chap 18 -->

<!-- # Chap 19 -->

<!-- # Chap 20 -->

<!-- # Chap 21 -->



# Respuestas Breves a Ejercicios Seleccionados {-}

#### Capítulo 1 {-}

**1.1**  
a(i). Media = 12,840, Mediana = 5,695 <br>  
a(ii). Desviación estándar = 48,836.7 = 3.8 veces la media. Los datos parecen estar sesgados.<br>  
b. Los gráficos no se presentan aquí. Al verlos, la distribución parece estar sesgada hacia la derecha.<br>  
c(i). Los gráficos no se presentan aquí. Al verlos, aunque la distribución se ha acercado a la simetría, todavía es bastante asimétrica.<br>  
c(ii). Los gráficos no se presentan aquí. Al verlos, sí, la distribución parece ser mucho más simétrica.<br>  
d. Media = 1,854.0, Mediana = 625.7, Desviación estándar = 3,864.3. Un patrón similar se mantiene para pacientes ambulatorios como para pacientes hospitalizados.<br>  

**1.2**. Parte 1. a. Estadísticas descriptivas para los datos de 2000  
$$
\small{
\begin{array}{lrrrrrrr}
   \hline
         &   & 1er  &   &    & 3er  &   & \text{Desviación} \\ 
         & \text{Mínimo}  & \text{Cuartil}  & \text{Mediana} & \text{Media}  & \text{Cuartil} & \text{Máximo}   & \text{Estándar} 
         \\\hline
   \text{TPY}   & 11.57 & 56.72 & 80.54 & 88.79 & 108.60 & 314.70 & 46.10 \\ 
   \text{NUMBED} & 18.00    & 60.25 & 90.00    & 97.08 & 118.8 & 320.00   & 48.99 \\ 
   \text{SQRFOOT} & 5.64  & 28.64 & 39.22 & 50.14 & 65.49 & 262.00   & 34.50 \\ 
    \hline
\end{array}
}
$$
b. Los gráficos no se presentan aquí. Al verlos, el histograma parece estar sesgado hacia la derecha, pero solo levemente.<br>  
c. Los gráficos no se presentan aquí. Al verlos, tanto el histograma como el gráfico $qq$ sugieren que la distribución transformada es cercana a una distribución normal.<br>  
Parte 2. a. Estadísticas descriptivas para los datos de 2001  
$$
\small{
\begin{array}{lrrrrrrr}
   \hline
         &   & 1er  &   &    & 3er  &   & \text{Desviación} \\ 
         & \text{Mínimo}  & \text{Cuartil}  & \text{Mediana} & \text{Media}  & \text{Cuartil} & \text{Máximo}   & \text{Estándar} 
         \\\hline
   \text{TPY}   & 12.31 & 56.89 & 81.13 & 89.71 & 109.90 & 440.70 & 49.05 \\ 
   \text{NUMBED} & 18.00    & 60.00    & 90.00    & 97.33 & 119.00   & 457.00   & 51.97 \\ 
   \text{SQRFOOT} & 5.64  & 28.68 & 40.26 & 50.37 & 63.49 & 262.00   & 35.56 \\ 
   \hline
\end{array}
}
$$
c. Tanto el histograma como el gráfico $qq$ (no presentados aquí) sugieren que la distribución transformada es cercana a una distribución normal.<br>  

**1.5**  
a. Media = 5.953, Mediana = 2.331<br>  
b. Los gráficos no se presentan aquí. Al verlos, el histograma parece estar sesgado hacia la derecha. El gráfico $qq$ indica una desviación seria de la normalidad.<br>  
c(i). Para ATTORNEY=1, tenemos Media = 9.863 y Mediana = 3.417. Para ATTORNEY=2, tenemos Media = 1.865 y Mediana = 0.986. Esto sugiere que las pérdidas asociadas con la intervención de un abogado (ATTORNEY=1) son mayores que cuando no hay un abogado involucrado (ATTORNEY=2).<br>  

**1.7**  
a. Los gráficos no se presentan aquí. Al verlos, el histograma parece estar sesgado hacia la izquierda. El gráfico $qq$ indica una desviación seria de la normalidad.<br>  
b. Los gráficos no se presentan aquí. Al verlos, la transformación hace poco para simetrizar la distribución.  

#### Capítulo 2 {-}  


**2.1**  
$r=0.5491, b_0=4.2054, b_1=0.1279$ <br>  

**2.3** a.  
\begin{eqnarray*} 0 & \leq &  
\frac{1}{n-1}\sum_{i=1}^n\left( a\frac{x_i-\overline{x}}{s_{x}}-c  
\frac{y_i-\overline{y}}{s_{y}}\right) ^{2} \\  
&=&{\frac{1}{n-1}}\sum_{i=1}^n\left[a^2\frac{(x_i-\overline{x})^2}{s_{x}^2}  
-2ac\frac{(x_i-\overline{x})(y_i-\overline{y})}{s_x s_{y}}+c^2\frac{(y_i-\overline{y})^2}{s_{y}^2} \right]\\  
&=& a^2\frac{1}{s_x^2}\frac{1}{n-1}\sum_{i=1}^n\left(x_i-\overline{x}\right)^2-2ac\frac{1}{s_x s_y}\frac{1}{n-1}\sum_{i=1}^n\left(x_i-\overline{x}\right)\left(y_i-\overline{y}\right)\\  
&&+~c^2\frac{1}{s_y^2}\frac{1}{n-1}\sum_{i=1}^n\left(y_i-\overline{y}\right)^2\\  
&=&a^2\frac{1}{s_x^2}s_x^2-2acr+c^2\frac{1}{s_y^2}s_y^2\\  
&=& a^{2}+c^{2}-2acr.  
\end{eqnarray*}  
b. Según la parte (a), tenemos $a^{2}+c^{2}-2acr \geq 0$.  
Así que,\begin{eqnarray*}  
a^{2}+c^{2}-2ac+2ac &\geq& 2acr\\  
(a-c)^2&\geq& 2acr-2ac\\  
(a-c)^2&\geq& 2ac(r-1)  
\end{eqnarray*}  
c. Usando el resultado en la parte b) y tomando $a = c$, podemos obtener $2a^{2}(r-1)\leq0$.  
Además, $a^2\geq 0$, por lo que $r-1\leq 0$. Así, $r \leq 1$.<br>  
d. Usando el resultado en la parte (b) y tomando $a = -c$, podemos obtener $-2a^{2}(r-1)\leq4a^2$.  
Además, $-2a^2\leq 0$, por lo que $r-1\geq -2$. Así, $r \geq -1$.<br>  
e. Si todos los datos se encuentran en una línea recta que pasa por los cuadrantes superior izquierdo e inferior derecho, entonces $r=-1$.  
Si todos los datos se encuentran en una línea recta que pasa por los cuadrantes inferior izquierdo y superior derecho, entonces $r=1$.<br>  


**2.5** a.  
\begin{eqnarray*} 
b_1 = r\frac{s_{y}}{s_{x}} &=& \frac{1}{(n-1)s_{x}^{2}}\sum_{i=1}^n\left( x_{i}-\overline{x}\right) \left( y_{i}-\overline{y}\right)  \\ 
&=& \frac{1}{\sum_{i=1}^n\left( x_{i}-\overline{x}\right)^{2}}\sum_{i=1}^n\left[\frac{y_{i}-\overline{y}}{x_{i}-\overline{x}}\left( x_{i}-\overline{x}\right)^2\right]\\ 
&& \\ 
&&\\ 
&=& \frac{\sum_{i=1}^nweight_i~slope_i}{\sum_{i=1}^nweight_{i}}. 
\end{eqnarray*}  
donde,  
$$
slope_i=\frac{y_{i}-\overline{y}}{x_{i}-\overline{x}}~~~~~\mathrm{y}~~~~~weight_i=\left( x_{i}-\overline{x}\right)^2 
$$  
b. $slope_1=-1.5, weight_1=4$<br>  

**2.7** a.  
Para el modelo en este ejercicio, la estimación de mínimos cuadrados de $\beta_1$ es el $b_1$ que minimiza la suma de cuadrados $\mathrm{SS}(b_1^{\ast} )=\sum_{i=1}^n\left( y_i - b_1^{\ast }x_i\right) ^{2}.$  
Entonces, tomando la derivada con respecto a $b_1^{\ast}$, tenemos  
$$
\frac{\partial }{\partial b_1^{\ast }}SS(b_1^{\ast })=\sum_{i=1}^n(-2x_{i})\left( y_{i}-b_1^{\ast }x_{i}\right)
$$  
Al igualar esta cantidad a cero y cancelar términos constantes, se obtiene  
$$
\sum_{i=1}^n\left(x_{i}y_{i}-b_1^{\ast }x_{i}^2\right) =0
$$  
Por lo tanto, concluimos que  
$$
b_1 = \frac{\sum_{i=1}^n x_i y_i}{\sum_{i=1}^nx_i^{2}}.
$$  
b. Del problema, tenemos $x_i = z_i^2$. Usando el resultado de la parte (a), podemos concluir que  
$$
b_1 = \frac{\sum_{i=1}^n z_i^2 y_i}{\sum_{i=1}^nz_i^{4}}.
$$  

**2.10**  
a(i). Correlación$= 0.9372$<br>  
a(ii). Tabla de correlaciones  
$$
\small{
\begin{array}{llll} 
   \hline
   &\text{TPY} &   \text{NUMBED} &  \text{SQRFOOT}  \\\hline
\text{TPY}  &   1.0000 & 0.9791 & 0.8244\\ 
\text{NUMBED} &  0.9791 & 1.0000 & 0.8192\\ 
\text{SQRFOOT} & 0.8244 & 0.8192 & 1.0000\\ 
  \hline
\end{array}
}
$$  
a(iii). Correlación$= 0.9791.$ Las correlaciones no se ven afectadas por los cambios de escala.<br>  
b. Los gráficos no se presentan aquí. Al verlos, existe una fuerte relación lineal entre NUMBED y TPY. La relación lineal entre SQRFOOT y TPY no es tan fuerte como la de NUMBED y TPY.<br>  
c(i). $b_1=0.92142, t-\mathrm{ratio}=91.346, R^2=0.9586$<br>  
c(ii). $R^2 =0.6797.$ El modelo que utiliza NUMBED es preferido.<br>  
c(iii). $b_1 =1.01231, t-\mathrm{ratio}=81.235, R^2=0.9483$<br>  
c(iv). $b_1 =0.68737, t-\mathrm{ratio}=27.25, R^2=0.6765$<br>  
Parte 2: $b_1=0.932384, t-\mathrm{ratio}=120.393, R^2=0.9762.$ El patrón es similar al informe de costos para el año 2000.<br>  

**2.11** $\hat{e}_1 = -23.$<br>  

**2.13**  
a.  
$$
\hat{y}_i - \overline{y} = (b_0 + b_1 x_i) - \overline{y} = (\overline{y}-b_1 \overline{x} + b_1 x_i) - \overline{y} = b_1(x_i - \overline{x}).
$$  
b.  
$$
\sum^n_{i=1}(y_i - \overline{y})^2 =
\sum^n_{i=1}(b_1(x_i - \overline{x}))^2 = b_1^2 \sum_{i=1}^n(x_i - \overline{x})^2 = b_1^2 s_x^2(n-1).
$$  
c.  
$$
R^2 = \frac{Regression ~SS}{Total ~SS} =
\frac{b_1^2 s_x^2(n-1)}{\sum_{i=1}^n(y_i - \overline{y})^2} =
\frac{b_1^2 s_x^2(n-1)}{s_y^2(n-1)} = \frac{b_1^2 s_x^2}{s_y^2}.
$$  


**2.15** a. A partir de la definición del coeficiente de correlación y del Ejercicio 2.8(b), tenemos  
$$
r(y,x)(n-1)s_y s_x = \sum_{i=1}^n \left( y_i-\overline{y}\right)
\left( x_i-\overline{x}\right) = \sum_{i=1}^n y_i x_i - n
\overline{x} \overline{y}.
$$
Si $\overline{y}=0,\overline{x}=0$ o ambos $\overline{x}$ y $\overline{y}=0$, entonces $r(y,x)(n-1)s_y s_x = \sum_{i=1}^n y_i x_i$. Por lo tanto, $r(y,x)=0$ implica
$\sum_{i=1}^ny_i x_i=0$\ y viceversa.<br>  
b.  
\begin{eqnarray*} 
\sum_{i=1}^n x_i e_i &=& \sum_{i=1}^n x_i (y_i - (\overline{y} + b_1(x_i-\overline{x}) )) \\ 
&=& \sum_{i=1}^n x_i (y_i - \overline{y}) - b_1 \sum_{i=1}^n x_i (x_i-\overline{x}) \\ 
&=& \sum_{i=1}^n x_i b_1(x_i - \overline{x}) - b_1 \sum_{i=1}^n x_i (x_i-\overline{x}) = 0, 
\end{eqnarray*}  
c.  
\begin{eqnarray*} 
\sum_{i=1}^n \widehat{y}_i e_i &=& \sum_{i=1}^n
( \overline{y}+b_1(x_i-\overline{x}) ) e_i \\ 
&=&  \overline{y} \sum_{i=1}^n e_i + b_1\sum_{i=1}^n ( (x_i-\overline{x})) e_i = 0, 
\end{eqnarray*}  

**2.17**  
Cuando $n = 100$, $k = 1$, $Error~SS = [n-(k+1)]s^2 = 98s^2$<br>  
a. $e_{10}^2/(Error~SS) = (8s)^2/(98s^2) = 65.31\%$<br>  
b. $e_{10}^2/(Error~SS) = (4s)^2/(98s^2) = 16.33\%$<br>  
Cuando $n = 20$, $k = 1$, $Error~SS = [n-(k+1)]s^2 = 18s^2$<br>  
c. $e_{10}^2/(Error~SS) = (4s)^2/(18s^2) = 88.89\%$<br>  

**2.20**  
a. Correlación=0.9830<br>  
Estadísticas descriptivas  
$$
\small{
\begin{array}
{lrrrrrrr}
   \hline
         &   & 1st  &   &    & 3rd  &   & \text{Desviación} \\ 
         & \text{Mínimo}  & \text{Cuartil}  & \text{Mediana} & \text{Media}  & \text{Cuartil} & \text{Máximo}   & \text{Estándar} 
         \\\hline
   \text{LOGTPY}   & 2.51 &  4.04 & 4.40 & 4.37 & 4.70 & 6.09 & 0.51 \\ 
   \text{LOGNUMBED} & 2.89    & 4.09 & 4.50    & 4.46 & 4.78 & 6.13   & 0.49 \\ 
   \hline
\end{array}
}
$$  
b. $R^2 = 0.9664$,  $b_1 = 1.01923$, $t(b_1) = 100.73$.<br>  
c(i). Los grados de libertad son $df = 355 - (1+1) = 353$. El valor $t$ correspondiente es 1.96. Como el estadístico $t$ $t(b_1) = 100.73 > 1.9667$, rechazamos $H_0$ a favor de la alternativa.<br>  
c(ii). El estadístico $t$ es $t - \mathrm{ratio} = (b_1 - 1)/se(b_1) = (1.01923 - 1)/0.01012 = 1.9002.$ Como $t-\mathrm{ratio} < 1.9667$, no rechazamos $H_0$ a favor de la alternativa.<br>  
c(iii). El valor $t$ correspondiente es 1.645. El estadístico $t$ es $t - \mathrm{ratio} = 1.9002.$ Rechazamos $H_0$ a favor de la alternativa.<br>  
c(iv). El valor $t$ correspondiente es -1.645. El estadístico $t$ es $t - \mathrm{ratio} = 1.9002.$ No rechazamos $H_0$ a favor de la alternativa.<br>  
d(i). Una estimación puntual es 2.0384<br>  
d(ii). El intervalo de confianza al 95\% para la pendiente $b_1$ es $1.0192 \pm 1.9667 \times 0.0101 = (0.9993, 1.0391)$. Un intervalo de confianza al 95\% para el cambio esperado de LOGTPY es $(0.9993 \times 2, 1.0391 \times 2) = (1.9987, 2.0781)$<br>  
d(iii). El intervalo de confianza al 99\% es $(2\times(1.0192 - 2.5898\times 0.0101), 2\times(1.0192 + 2.5898\times 0.0101) =(1.9861, 2.0907) $<br>  
e(i). $\widehat{y} = -0.1747 + 1.0192 \times \ln 100 = 4.519037.$ <br>  
e(ii). El error estándar de la predicción  
$$
se(pred) = s \sqrt{1+\frac{1}{n}+\frac{\left( x^{\ast }-\overline{x}\right) ^{2} }{(n-1)s_{x}^{2}}} =
0.09373 \sqrt{1+\frac{1}{355}+\frac{\left( \ln(100)-4.4573\right) ^{2} }{(355-1)0.4924^{2}}}=0.0938.
$$  
e(iii). El intervalo de predicción al 95\% en $x^*$ es  
$$
\widehat{y}^{\ast } \pm t_{n-2,1-\alpha /2} ~se(pred) = 4.519037 \pm
1.9667(0.0938) = (4.3344, 4.7034).
$$  
e(iv).  La predicción puntual es $e^{4.519037}= 91.747$. <br>  
El intervalo de predicción es $(e^{4.334405}=76.280, e^{4.703668}=110.351 ).$<br>  
e(v).  El intervalo de predicción es $(e^{4.364214}=78.588, e^{4.673859}=107.110 ).$<br>  


**2.22**  
a. Ajustado US $LIFEEXP = 83.7381 - 5.2735 \times 2.0 = 73.1911$<br>  
b. Un intervalo de predicción al 95\% para la esperanza de vida en Dominica es  
$$
\widehat{y}_{\ast} \pm t_{n-2,1-\alpha /2} ~se(pred)=73.1911\pm(1.973)(6.642)=(60.086, 86.296)
$$  
c.  
$$
e_{i}=y_{i}-\widehat{y}_{i}=y_{i}-\left(
b_0+b_1x_{i}\right)= 72.5-(83.7381 - 5.2735 \times 1.7)=-2.273
$$  
Este residual es 2.273/6.615 = 0.3436 múltiplos de $s$ por debajo de cero.<br>  
d. Probar $H_0: \beta_1 = -6.0$ frente a $H_a: \beta_1 > -6.0$ al nivel de significancia del 5\% usando un valor $t$ = 1.645. El estadístico $t$ calculado $= \frac{-5.2735-(-6)}{0.2887}=2.5165$, que es $\geq1.645$. Por lo tanto, rechazamos $H_0$ a favor de la alternativa. El valor $p$ correspondiente $= 0.00637$.  

#### Capítulo 3 {-}  

**3.1**. a. $R^2_a = 1 - s/{s^2_y} = 1 - {(50)^2}/{(100)^2} = 1 - 1/4 = 0.75.$<br>  
b. $Total ~SS =(n - 1)s^2_y = 99(100)^2 = 990000$ y <br>  
$Error ~SS = (n - (k + 1))s^2 = (100 - (3 + 1))(50)^2 = 240000.$<br>  
$$
\small{
\begin{array}{lcrcc}
 \hline
Fuente & SS & df & MS & F \\ \hline
\text{Regresión} & 750000 & 3 & 250000 & 100 \\  
\text{Error} & 240000 & 96 & 2500 & \\  
\text{Total} & 990000 &99 && \\  
 \hline
 \end{array}
}
$$  
c. $R^2 = (Regression~SS)/(Total~SS) =750000/990000 = 75.76\%$.<br>  

**3.3** a. ${\bf y}=(0~1~5~8)^{\prime}$, $\mathbf{X}=\left(
                                       \begin{array}{ccc}
                                         1 & -1 & 0 \\  
                                         1 & 2  & 0 \\  
                                         1 & 4  & 1 \\  
                                         1 & 6  & 1 \\  
                                       \end{array}
                                     \right)$.<br>  
b. $\hat{y}_{3}=x^{\prime}_{3}\mathbf{b}=(1~4~1)\left(
                                                      \begin{array}{c}
                                                        0.15 \\  
                                                        0.692 \\  
                                                        2.88 \\  
                                                      \end{array}
                                                    \right)=5.798$
                                                    <br>  
c. $se(b_{2})=s\sqrt{3rd~diagonal~element~of~(\mathbf{X^{\prime }X)}^{-1}} = 1.373\sqrt{4.11538}=2.785$<br>  
d. $t(b_1)=b_1/se(b_1)=0.692/(1.373\times\sqrt{0.15385})=1.286$<br>  


**3.6**  
a. El coeficiente de regresión es -0.1846, lo que significa que cuando los gastos en educación pública aumentan en un 1\% del PIB, se espera que la esperanza de vida disminuya en 0.1846 años, manteniendo constantes las demás variables.<br>  
b. El coeficiente de regresión es -0.2358, lo que significa que cuando los gastos en salud aumentan en un 1\% del PIB, se espera que la esperanza de vida disminuya en 0.2358 años, manteniendo constantes las demás variables.<br>  
c. $H_{0}:\beta_2=0, H_{1}:\beta_2\neq0$. No podemos rechazar la hipótesis nula porque el valor $p$ es mayor que el nivel de significancia, digamos 0.05. Por lo tanto, PUBLICEDUCATION no es una variable estadísticamente significativa.<br>  
d(i). El propósito del gráfico de variables añadidas es explorar la correlación entre PUBLICEDUCATION y LIFEEXP después de eliminar los efectos de otras variables.<br>  
d(ii). La correlación parcial es  
$$
r=\frac{t(b_2)}{\sqrt{t(b_2)^2+n-(k+1)}}=\frac{-0.6888}{\sqrt{-0.6888^2+152-(3+1)}}=-0.0565 .
$$  

#### Capítulo 4 {-}  

**4.1**  
a. $R^2 = (Regression~SS)/(Total~SS)$.<br>  
b. $F$-ratio=$(Regression~MS)/(Error~MS)$.<br>  
c.  
$$
1-R^2 =
\frac{Total~SS}{Total~SS}-\frac{Regression~SS}{Total~SS}=
\frac{Error~SS}{Total~SS}.
$$  
Ahora, desde el lado derecho, tenemos  
\begin{align*}
\frac{R^2}{1-R^2} \frac{(n-(k+1))}{k}
&=\frac{(Regression~SS)/(Total~SS)}{(Error~SS)/(Total~SS)}\frac{(n-(k+1))}{k}\\
&= \frac{Regression~SS}{Error~SS}\frac{(n-(k+1))}{k}\\
&=\frac{(Regression~SS)/k}{(Error~SS)/(n-(k+1))}\\
&=\frac{Regression~MS}{Error~MS} = F-\mathrm{ratio}.
\end{align*}<br>  
d. $F-\mathrm{ratio}=1.7.$<br>  
e. $F-\mathrm{ratio}=19.7.$<br>  

**4.3**  
a. El tercer nivel de la estructura organizacional será capturado por el término de intercepción de la regresión.<br>  
b. $H_0$:TAXEXEMPT no es importante, $H_1$: TAXEXEMPT es importante. $p= 0.7694>0.05$, no rechazamos la hipótesis nula.<br>  
c. Dado que el valor $p = 1.74e^{-6}$ es menor que el nivel de significancia $\alpha=0.05$, MCERT es un factor importante para determinar LOGTPY.<br>  
c(i). La estimación puntual de LOGTPY es 3.988.<br>  
c(ii). El intervalo de confianza al 95\% es  
$ 3.988 \pm 1.967\times\ \sqrt{0.245}/(\sqrt{36}) = (3.826, 4.150)$.<br>  
d. $R^2=0.1448$. Todas las variables son estadísticamente significativas.<br>  
e. $R^2= 0.9673$. Solo LOGNUMBED es estadísticamente significativo a $\alpha=0.05$.<br>  
e(i). La correlación parcial es 0.0744. La correlación entre LOGTPY y LOGSQRFOOT es 0.8151. La correlación parcial elimina el efecto de otras variables en LOGTPY.<br>  
e(ii). El $t$-ratio prueba si la variable explicativa individual es estadísticamente significativa. El $F$-ratio prueba si las variables explicativas tomadas en conjunto tienen un impacto significativo en la variable de respuesta. En este caso, solo LOGNUMBED es significativa y el $R^2$ es alto, esto explica por qué el $F$-ratio es grande mientras que la mayoría de los $t$-ratios son pequeños.<br>


**4.7**  
a. $H_0$: PUBLICEDUCATION y lnHEALTH no son conjuntamente estadísticamente significativos. Es decir, los coeficientes de las dos variables son iguales a cero. $H_1$: PUBLICEDUCATION y lnHEALTH son conjuntamente estadísticamente significativos. Al menos uno de los coeficientes de las dos variables no es igual a cero. Para tomar la decisión, comparamos las estadísticas $F$ con el valor crítico. Si las estadísticas $F$ son mayores que el valor crítico, rechazamos la hipótesis nula. De lo contrario, no lo hacemos.<br>  
$F-ratio = (6602.7 - 6535.7)/(2 \times 44.2) = 0.76$.  
El 95\% de la distribución $F$ con $df_1=2$ y $df_2=148$ es aproximadamente 3.00. Dado que el $F-ratio$ es menor que el valor crítico, no podemos rechazar la hipótesis nula. Es decir, PUBLICEDUCATION y lnHEALTH no son conjuntamente significativos.<br>  
b. Podemos ver que la esperanza de vida varía entre diferentes regiones.<br>  
c. $H_0$: $\beta_{REGION}=0$, $H_1$: $\beta_{REGION}\neq0$. Para tomar la decisión, comparamos el valor $p$ con el nivel de significancia $\alpha=0.05$. Si $p<\alpha$, rechazamos la hipótesis nula. De lo contrario, no lo hacemos. En este caso, $p=0.000 < 0.05$, por lo que rechazamos la hipótesis nula. REGION es un determinante estadísticamente significativo de LIFEEXP.<br>  
d(i). Si REGION=Abrab state, $\widehat{LIFEEXP} = 83.3971-2.7559 \times 2-0.4333\times 5-0.7939\times 1=74.9249$.  
Si REGION=Sub-Sahara Africa, $\widehat{LIFEEXP} = 83.3971-2.7559\times 2-0.4333 \times 5-0.7939 \times 1 -14.3567 = 60.5682$.<br>  
d(ii). El intervalo de confianza al 95\% es $-14.3567\pm 1.976\times 1.8663=(-18.044,-10.669).$<br>  
d(iii). La estimación puntual para la diferencia es 18.1886.  

#### Capítulo 5 {-}  

**5.1**  
a. De la ecuación (2.9), tenemos  
\begin{eqnarray*}
h_{ii} & = & \mathbf{x_i}^{\prime}\left(\mathbf{X}^{\prime }\mathbf{X}\right)^{-1}\mathbf{x_i}\\
&=&\left(\begin{array}{cc}1 & x_i\end{array}\right)
\frac{1}{ \sum_{i=1}^{n}x_i^2-n\overline{x}^2}
\left(\begin{array}{cc}n^{-1}\sum_{i=1}^{n}x_i^2 & -\overline{x} \\-\overline{x} & 1\end{array}\right)
\left(\begin{array}{c}1 \\x_i\end{array}\right)\\
&=& \frac{1}{\sum_{i=1}^{n}x_i^2-n\overline{x}^2} \left(
n^{-1}(\sum_{i=1}^{n}x_i^2-n\overline{x}^2)+\overline{x}^2-2\overline{x}x_i+x_i^2
\right)\\
&=&\frac{1}{n}+\frac{(x_i-\overline{x})^2}{(n-1)s_x^2} .
\end{eqnarray*}  

b. El promedio del leverage es  
$$
\bar{h}=\frac{1}{n} \sum_{i=1}^n h_{ii} =
\frac{1}{n}+\frac{1}{n}\sum_{i=1}^n\frac{(x_i-\bar{x})^2}{(n-1)s_{x}^2}=\frac{1}{n}+\frac{1}{n}=\frac{2}{n}
$$  

c. Sea $c = (x_i-\bar{x})/s_x$. Entonces,  
$$
\frac{6}{n}=h_{ii}=\frac{1}{n}+\frac{(x_i-\bar{x})^2}{(n-1)s_{x}^2} = 
\frac{1}{n}+\frac{(cs_x)^2}{(n-1)s_{x}^2}=\frac{1}{n}+\frac{c^2}{n-1} .
$$  
Para $n$ grande, $x_i$ está aproximadamente a $c=\sqrt{5}=2.236$ desviaciones estándar del promedio.  

**5.3**  
a. Los gráficos no se presentan aquí. Al observarlos, es difícil detectar patrones lineales en el gráfico de GDP versus LIFEEXP. La transformación logarítmica de GDP distribuye los valores de GDP, permitiéndonos ver patrones lineales. Argumentos similares se aplican a HEALTH, donde el patrón en lnHEALTH es más lineal.<br>  
c(ii). Es ambos. El residual estandarizado es -2.66, que excede el umbral de 2, en valor absoluto. El leverage es 0.1529, que es mayor que el umbral $3 \times\overline{h} =3\times (k+1)/n = 0.08$.<br>  
c(iii). La variable PUBLICEDUCATION ya no es estadísticamente significativa.


#### Capítulo 6 {-}

**6.1**  
a. La variable involact está algo sesgada hacia la derecha, pero no de manera drástica. La variable involact tiene varios ceros que pueden ser un problema con variables dependientes limitadas. La variable age parece ser bimodal, con seis observaciones de 28 años o menos y las demás mayores o iguales a 40 años.  
$$
\small{
\begin{array}{lrrrrrrr}
   \hline
       &   &  & \text{Desviación} \\ 
       &  \text{Media}  &  \text{Mediana} & \text{Estándar} & \text{Mínimo} & \text{Máximo}\\
   \hline
\text{race}  &   34.9    &   24.5 &  32.6  &      1.0  &     99.7\\
\text{fire}   &   12.3    &   10.4 &   9.3  &      2.0  &     39.7\\
\text{theft}  &   32.4    &   29.0 &  22.3  &      3.0  &    147.0\\
\text{age}    &   60.3    &   65.0 &  22.6  &      2.0  &     90.1\\
\text{income} &   10,696  &  10,694.0 & 2,754  &    5,583 &   21,480\\
\text{volact}  &  6.5    &    5.9  &  3.9     &   0.5    &   14.3\\
\text{involact} & 0.6   &     0.4  &  0.6     &   0.0    &    2.2\\
   \hline
\end{array}
}
$$  
b. La matriz de dispersión (no presentada aquí) muestra una relación negativa entre volact e involact, una relación negativa entre race y volact, y una relación positiva entre race e involact. Si existiera discriminación racial, esperaríamos que los códigos postales con más minorías tuvieran menos acceso al mercado voluntario (menos costoso), lo que significa que tendrían que recurrir al mercado involuntario para obtener seguro.  

c. Tabla de correlaciones  
$$
\small{
\begin{array}{lrrrrrrr}
   \hline
       &    \text{race}&  \text{fire}  &\text{theft} &   \text{age} & \text{income} &\text{volact} &\text{involact}\\
   \hline
\text{race}  &   1.000 &   & &  &  &  &\\
\text{fire}   &   0.593 & 1.000  & & &  &  &\\
\text{theft}  &   0.255 & 0.556  &1.000 &  &  &  &\\
\text{age}    &   0.251 & 0.412  &0.318 & 1.000 &  &  &\\
\text{income} &  -0.704 &-0.610 &-0.173 &-0.529 & 1.000  &  &\\
\text{volact} &  -0.759 &-0.686 &-0.312 &-0.606 & 0.751  &1.000   &\\
\text{involact} & 0.714 & 0.703 & 0.150 & 0.476 & -0.665 &-0.746  &  1.000\\
   \hline
\end{array}
}
$$
d(i). El coeficiente asociado con race es negativo y estadísticamente significativo.<br>
d(ii). Los códigos postales con alta influencia son el número 7 y 24. La variable race sigue siendo estadísticamente significativa y negativa. La variable fire ya no es significativa, aunque income se vuelve significativa.<br>
e. La variable race sigue siendo positiva y estadísticamente significativa. De manera similar, el papel de las otras variables no cambia dependiendo de la presencia de los dos puntos de alta influencia.<br>
f. La variable race sigue siendo positiva y estadísticamente significativa. De manera similar, el papel de las otras variables no cambia dependiendo de la presencia de los dos puntos de alta influencia.<br>
g. La influencia depende de las variables explicativas, no de las variables dependientes. Como las variables explicativas permanecieron sin cambios en los tres análisis, las influencias permanecieron sin cambios.<br>
h. La demanda de seguros depende del tamaño de la pérdida a asegurar, la capacidad del solicitante de pagarla y el conocimiento de los contratos de seguros. Para los seguros de vivienda, el tamaño de la pérdida se relaciona con el precio de la vivienda, el tipo de estructura, las precauciones de seguridad disponibles y la susceptibilidad a catástrofes como tornados, inundaciones, etc. La capacidad de pago se basa en ingresos, patrimonio, número de dependientes y otros factores. El conocimiento de los contratos de seguros depende, por ejemplo, de la educación. Todos estos factores omitidos pueden estar relacionados con race.<br>
i. Se esperaría que los códigos postales contiguos compartieran experiencias económicas similares. Podríamos subdividir la ciudad en grupos homogéneos, como el centro de la ciudad y los suburbios. También podríamos realizar mínimos cuadrados ponderados donde los pesos estén dados por la distancia al centro de la ciudad.

#### Capítulo 7 {-}

**7.1**  
a. \begin{align*}
\textrm{E}~y_t &= \textrm{E}~(y_0+c_1+\cdots+c_t)=\textrm{E}~y_0+\textrm{E}~c_1+\cdots+\textrm{E}~c_t\\
&= y_0+\mu_c+\cdots+\mu_c = y_0 + t \mu_c.
\end{align*}

b. \begin{align*}
\textrm{Var}~y_t &= \textrm{Var}~(y_0+c_1+\cdots+c_t)=\textrm{Var}~c_1+\cdots+\textrm{Var}~c_t\\
&=\sigma_c^2+\cdots+\sigma_c^2 = t\sigma_t^2.
\end{align*}

**7.3**  
a(ii). No. Hay una tendencia clara hacia la baja en la serie, lo que indica que la media cambia con el tiempo.<br>
b(i). Los $t-$ratios asociados con las porciones de tendencia lineal y cuadrática son altamente significativos desde el punto de vista estadístico. El $R^2 = 0.8733$ indica que el modelo se ajusta bien.<br>
b(ii). El signo de un residuo es muy probable que sea el mismo que el de los residuos precedentes y posteriores. Esto sugiere un alto grado de autocorrelación en los residuos.<br>
b(iii). $\widehat{EURO_{702}} = 0.808 + 0.0001295(702) - 4.639 \times 10^{-7}(702)^2 = 0.6703.$<br>
c(i). Este es un modelo de caminata aleatoria.<br>
c(ii). $\widehat{EURO_{702}} = 0.6795 + 3(-0.0001374) = 0.679088.$<br>
c(iii). Un intervalo de predicción aproximado al 95\% para $EURO_{702}$ es
$$
0.679088\pm2(0.003621979)\sqrt{3} \approx (0.66654, 0.691635).
$$

#### Capítulo 8 {-}

**8.1**  
$$
\begin{array}{ll}
r_1 &=\left(\sum_{t=2}^{5}(y_{t-1}-\bar y)(y_{t}-\bar
y)\right) /\left(\sum_{t=1}^{5}(y_{t}-\bar y)^{2}\right) = -0.0036/0.0134 = -0.2687 \\ 
r_2 &= \left(\sum_{t=3}^{5}(y_{t-2}-\bar y)(y_{t}-\bar
y)\right) /\left(\sum_{t=1}^{5}(y_{t}-\bar y)^{2}\right) = 0.0821 
\end{array}
$$

**8.3**  
a. $b_1= \left(\sum_{t=2}^{T}(y_{t-1}-\bar
y_{-})(y_t-\bar y_{+})\right) /\left(\sum_{t=2}^{T}(y_{t-1}-\bar
y_{-})^2\right)$,\newline
donde $\bar y_{+}=\left(\sum_{t=2}^{T}y_{t}\right)/(T-1)$ y $\bar y_{-}=\left(\sum_{t=1}^{T-1}y_{t} \right)/(T-1)$.<br>
b. $b_0=\bar y_{+}-b_1 \bar y_{-}$.<br>
c. $b_0\approx \bar y \left[ 1- \left(\sum_{t=2}^{T}(y_{t-1}-\bar
y_{-})(y_t-\bar y_{+})\right) /\left(\sum_{t=2}^{T}(y_{t-1}-\bar
y_{-})^2\right) \right] \approx \bar y \left[1-r_1\right]$.


**8.6**  
a. Dado que la media y la varianza de la secuencia no varían con el tiempo, se puede considerar que la secuencia es débilmente estacionaria.<br>
b. Las estadísticas resumen de la secuencia son las siguientes:
$$
\small{
\begin{array}{rrrrr} \hline
\text{Media}& \text{Mediana}& \text{Desv. Estándar}& \text{Mínimo}& \text{Máximo}\\
0.0004& 0.0008& 0.0064& -0.0182 & 0.0213\\
\hline
\end{array}
}
$$
Bajo la suposición de ruido blanco, el pronóstico de una observación en el futuro es su media muestral, es decir, 0.0004. Este pronóstico no depende del número de pasos hacia adelante.<br>
c. Las autocorrelaciones para los rezagos 1 a 10 se muestran a continuación:
$$
\small{
\begin{array}{ccccccccccc}
\hline
         0   &   1  &    2  &    3   &   4   &   5   &   6   &   7   &   8   &   9   &  10\\
     1.000 & -0.046 & -0.096 & 0.019 & -0.002 &  -0.004 & -0.054 & -0.035 & -0.034 & -0.051 & 0.026\\
\hline
\end{array}
}
$$
Dado que $|r_k/se(r_k)|<2$ ($se(r_k)=1/\sqrt{503} = 0.0446$) para $i=1,\ldots,10$, ninguna de las autocorrelaciones es fuertemente estadísticamente significativa diferente de cero, excepto para el rezago 2. Para el rezago 2, la autocorrelación es $0.096/0.0446 = 2.15$ errores estándar por debajo de cero.

#### Capítulo 11 {-}

**11.1**  
a. La función de densidad de probabilidad es
$$
\mathrm{f}(y)=\frac{\partial}{\partial y}\mathrm{F}(y)
=(-1)(1+e^{-y})^{-2}e^{-y}(-1)= \frac{e^y}{(1+e^y)^2}.
$$
b.
$$
\mu_y = \int_{-\infty}^{\infty}\ y \mathrm{f}(y)dy =
\int_{-\infty}^{\infty}\ y \frac{e^{y}}{(1+e^{y})^{2}}dy= 0.
$$
c.
$$
\mathrm{E~}y^2 = \int_{-\infty}^{\infty}\ y^2 \mathrm{f}(y)dy =
\pi^2 /3 .
$$
Dado que $\mu_y = 0$, la desviación estándar es $\sigma_y = \pi / \sqrt{3}=1.813798.$ <br>
d. La función de densidad de probabilidad para $y^{\ast \ast}$ es<br>
\begin{eqnarray*}
\mathrm{f}^{\ast}(y)&=& \frac{\partial}{\partial y}\Pr(y^{\ast \ast}
\leq y) = \frac{\partial}{\partial y}\Pr(y^{\ast } \leq y \sigma_y +
\mu_y) =\sigma_y \mathrm{f}(y \sigma_y) = \sigma_y
\frac{e^{y\sigma_y}}{(1+e^{y\sigma_y})^2}.
\end{eqnarray*}


**11.3**  
Sea $\Pr(\varepsilon_{i1} \leq a) = F(a)=\exp(-e^{-a})$ y $f(a)=\frac{dF(a)}{da}=\exp(-e^{-a})e^{-a}.$ Entonces

\begin{align*}
\Pr(\varepsilon_{i2}-\varepsilon_{i1} \leq a)
&=\int_{-\infty}^{\infty}F(a+y)f(y)\,dy=\int_{-\infty}^{\infty}\exp\left[-e^{-y}(e^{-a}+1)\right]e^{-y}\,dy\\
&=\int_{\infty}^0\exp(-zA)z \,d(-\ln z)=-\int_{\infty}^0\exp(-zA)\,dz\\
&= \frac{\exp(-zA)}{A}|_\infty^0=\frac{1}{A}=\frac{1}{1+e^{-a}},
\end{align*}
con $A=e^{-a}+1$ y $z=e^{-y}$. Así,

$$
\pi_i=\Pr (\epsilon _{i2}-\epsilon _{i1}<V_{i1}-V_{i2})=\Pr
(\epsilon _{i2}-\epsilon _{i1}<\mathbf{x}_i^{\mathbf{\prime
}}\boldsymbol \beta) =\frac{1}{1+\exp (-\mathbf{x}_i^{\mathbf{\prime
}}\boldsymbol \beta)}.
$$

**11.5**  
De la ecuación (11.5) sabemos que

$$
\sum\limits_{i=1}^{n}\mathbf{x}_i\left( y_i-\mathrm{\pi }(\mathbf{x}
_i^{\mathbf{\prime}}\mathbf{b}_{MLE})\right) =
\sum\limits_{i=1}^{n}(1~~x_{i1}~~\cdots~~x_{ik})^\prime \left(
y_i-\mathrm{\pi }(\mathbf{x}
_i^{\mathbf{\prime}}\mathbf{b}_{MLE})\right)
=(0~~0~~\cdots~~0)^{\prime}.
$$

De la primera fila, obtenemos $\sum\limits_{i=1}^{n} \left(
y_i-\mathrm{\pi }(\mathbf{x}
_i^{\mathbf{\prime}}\mathbf{b}_{MLE})\right) =0$. Dividiendo por $n$
se obtiene $\overline{y} = n^{-1} \sum_{i=1}^n \widehat{y}_i .$


**11.7**  
a. La derivada de la función logit es
$$
\frac{\partial}{\partial y}\mathrm{\pi}(y) =
\mathrm{\pi}(y)\frac{1}{(1+e^y)}=\mathrm{\pi}(y)(1-\mathrm{\pi}(y)).
$$
Por lo tanto, usando la regla de la cadena y la ecuación (11.5), tenemos
$$
\begin{array}{ll}
\mathbf{I}(\boldsymbol \beta) &=&  - \mathrm{E~}\frac{\partial
^{2}}{\partial \boldsymbol \beta\partial \boldsymbol \beta ^{\prime
}}L(\boldsymbol \beta) = -\mathrm{E~} \frac{\partial }{\partial
\boldsymbol \beta^{\prime}} \left(
\sum\limits_{i=1}^{n}\mathbf{x}_i\left( y_i-\mathrm{\pi }(\mathbf{x}
_i^{\mathbf{\prime }}\boldsymbol \beta)\right) \right) \\ 
&=& \sum\limits_{i=1}^{n}\mathbf{x}_i \frac{\partial }{\partial
\boldsymbol \beta^{\prime}} \mathrm{\pi }(\mathbf{x}
_i^{\mathbf{\prime }}\boldsymbol \beta)
=\sum\limits_{i=1}^{n}\mathbf{x}_i \mathbf{x}_i^{\prime}
\mathrm{\pi}(\mathbf{x} _i^{\mathbf{\prime}}\boldsymbol
\beta)(1-\mathrm{\pi}(\mathbf{x} _i^{\mathbf{\prime}}\boldsymbol
\beta)).
\end{array}
$$
Esto proporciona el resultado con $\sigma_i^2 = \mathrm{\pi}(\mathbf{x}_i^{\prime} \boldsymbol
\beta)(1-\mathrm{\pi}(\mathbf{x}_i^{\prime}\boldsymbol \beta))$.<br>

b. Definir $\mathbf{a}_i=\mathbf{x}_i\left( y_i-\mathrm{\pi }(\mathbf{x} _i^{\mathbf{\prime}}\boldsymbol \beta)\right)$ y
$\mathbf{H}_i = \frac{\partial }{\partial \boldsymbol \beta^{\prime}}\mathbf{a}_i =-\mathbf{x}_i \mathbf{x}_i^{\mathbf{\prime}} \mathrm{\pi }^{\prime}( \mathbf{x}_i^{\mathbf{\prime}}\boldsymbol \beta).$ <br>
Nótese que
$\mathrm{E}(\mathbf{a}_i)=\mathbf{x}_i \mathrm{E}\left( y_i-\mathrm{\pi }(\mathbf{x} _i^{\mathbf{\prime}}\boldsymbol \beta)\right)= \mathbf{0}$. Además, definimos $b_i=\frac{\mathrm{\pi
}^{\prime}( \mathbf{x}_i^{\mathbf{\prime}}\boldsymbol
\beta)}{\mathrm{\pi }(\mathbf{x} _i^{\mathbf{\prime}}\boldsymbol
\beta)(1-\mathrm{\pi }(\mathbf{x}_i^{ \mathbf{\prime}}\boldsymbol
\beta))}$. Con esta notación, la función de score es $\frac{\partial
}{\partial \boldsymbol \beta}L(\boldsymbol \beta) =
\sum\limits_{i=1}^{n} \mathbf{a}_i b_i$. Así,
$$
\begin{array}{ll}
\mathbf{I}(\boldsymbol \beta) & =  - \mathrm{E} \left(
\frac{\partial^2}{\partial \boldsymbol \beta ~ \partial \boldsymbol \beta ^{\prime}}L(\boldsymbol \beta) \right) = - \mathrm{E} \left( \frac{\partial}{\partial \boldsymbol \beta^{\prime}}\sum\limits_{i=1}^{n} \mathbf{a}_i b_i\right) \\ 
&= - \mathrm{E} \left( \sum\limits_{i=1}^{n} \left( \left(\frac{\partial}{\partial \boldsymbol
\beta^{\prime}}\mathbf{a}_i \right) b_i + \mathbf{a}_i \frac{\partial}{\partial \boldsymbol \beta^{\prime}}b_i \right) \right) 
= - \sum\limits_{i=1}^{n} \left[\mathrm{E}(\mathbf{H}_i)b_i + \mathrm{E}(\mathbf{a}_i)
\frac{\partial}{\partial \boldsymbol \beta^{\prime}}b_i \right] \\ 
&=  - \sum\limits_{i=1}^{n} \mathbf{H}_i b_i  =  \sum\limits_{i=1}^{n} \mathbf{x}_i \mathbf{x}_i^{\mathbf{\prime}} \frac {\left( \mathrm{\pi }^{\prime}( \mathbf{x}_i^{\mathbf{\prime}}\boldsymbol \beta)\right)^2} {\mathrm{\pi }(\mathbf{x} _i^{\mathbf{\prime}}\boldsymbol \beta)(1-\mathrm{\pi }(\mathbf{x}_i^{ \mathbf{\prime}}\boldsymbol \beta))} . 
\end{array}
$$

**11.8**  
a(i). Los gráficos no se presentan aquí.
$$
\small{
\begin{array}{lrrrrrrr}
   \hline
       &  mean  &  median & std & minimum & maximum\\
   \hline
\text{CLMAGE}    & 32.531  &   31.000  &  17.089  &    0.000  &     95.000\\
\text{LOSS}      &  5.954  &    2.331  &  33.136  &    0.005  &   1067.700\\
   \hline
\end{array}
}
$$
a(ii). No para CLMAGE, pero ambas versiones de LOSS parecen diferir por ATTORNEY.
$$
\small{
\begin{array}{crrr}
   \hline
   \text{ ATTORNEY}   & \text{CLMAGE} &  \text{LOSS} & \text{lnLOSS} \\ 
   \hline
      1 & 32.270  & 9.863   & 1.251\\
      2 & 32.822  & 1.865   & -0.169\\
   \hline
\end{array}
}
$$
a(iii). SEATBELT y CLMINSUR parecen ser diferentes, CLMSEX y MARITAL menos.


$$
\small{
\begin{array}{cccccccc}
\hline
  \text{ATTORNEY} &  \text{CLMSEX} & & \text{MARITAL} &&&  & \text{CLMINSUR} &  &  \text{SEATBELT} \\
           &          1 &          2 &          1 &          2 &          3 &          4 &          1 &          2 &          1 &          2 \\
\hline
         1 &        325 &        352 &        320 &        329 &          6 &         20 &         76 &        585 &        643 &         16 \\
         2 &        261 &        390 &        304 &        321 &          9 &         15 &         44 &        594 &        627 &          6 \\
\hline
\end{array}
}
$$
a(iv). El número de valores faltantes se muestra como:

$$
\small{
\begin{array}{cccccc}
\hline
\text{CLMAGE}  &  \text{LOSS} & \text{CLMSEX} & \text{MARITAL}& \text{CLMINSUR} & \text{SEATBELT}\\
                   189         &     12         &   16          &         41        &        48       &      NA\\
\hline
\end{array}
}
$$
b(i). La variable CLMSEX es estadísticamente significativa. La razón de probabilidades es $\exp(-0.3218) = 0.7248$, lo que indica que las mujeres tienen un 72\% de probabilidad de usar un abogado en comparación con los hombres (o los hombres tienen 1/0.72 = 1.379 veces más probabilidades de usar un abogado que las mujeres).<br>
b(ii). CLMSEX y CLMINSUR son estadísticamente significativas, y SEATBELT es algo significativo, según los valores $p$. CLMAGE no es significativo. MARITAL no parece ser estadísticamente significativo.<br>
b(iii). Los hombres usan abogados con más frecuencia: la razón de probabilidades es $\exp(-0.37691) = 0.686$, lo que indica que las mujeres tienen un 68.6\% de probabilidad de usar un abogado en comparación con los hombres.<br>
b(iv). La versión logarítmica, lnLOSS, es más importante. En el modelo final sin LOSS, el valor $p$ asociado con lnLOSS fue muy pequeño ($< 2e-16$), lo que indica una fuerte significación estadística.<br>
b(v). Todas las variables permanecen iguales excepto una de las variables binarias de MARITAL, que se vuelve marginalmente estadísticamente significativa. La principal diferencia es que estamos utilizando 168 observaciones adicionales al no requerir que CLMAGE esté en el modelo.<br>
b(vi). Para el componente sistemático, tenemos:
$$
\begin{array}{llll}
\mathbf{x}^{\prime}\mathbf{b}_{MLE} 
&= 0.75424 \\ 
&~~~ -0.51210* (\text{CLMSEX}=2)& +  0.04613*(\text{MARITAL}=2) \\ 
&~~~+ 0.37762*(\text{MARITAL}=3) &+ 0.12099*(\text{MARITAL}=4) \\ 
&~~~+ 0.13692*(\text{SEATBELT}=2) &-0.52960*(\text{CLMINSUR}=2)  \\ 
&~~~-0.01628* \text{CLMAGE} &+ 0.98260*\text{lnLOSS} \\ 
&= 1.3312.
\end{array}
$$
La probabilidad estimada de usar un abogado es
$$
\widehat{\pi} = \frac {\exp (1.3312)}{1+\exp (1.3312)} = 0.791.
$$
c. Las mujeres tienen menos probabilidades de usar abogados. Aquellos que no usan cinturón de seguridad (SEATBELT=2) tienen más probabilidades de usar un abogado (aunque no es significativo). Los solteros (MARITAL=2) tienen más probabilidades de usar un abogado. Los reclamantes asegurados (CLMINSUR=2) tienen menos probabilidades de usar un abogado. A mayor pérdida, mayor es la probabilidad de que un abogado esté involucrado.


**11.11** a. El intercepto y las variables PLACE\%, MSAT, RANK son significativas al nivel del 5\%.<br>
b(i). La probabilidad de éxito para este caso es 0.482. <br>
b(ii). La probabilidad de éxito para este caso es 0.281. <br>
b(iii). La probabilidad de éxito para este caso es 0.366. <br>
b(iv). La probabilidad de éxito para este caso es 0.497. <br>
b(v). La probabilidad de éxito para este caso es 0.277. <br>

#### Chapter 12 {-}

**12.1** Tomamos la derivada de la ecuación (12.2) con respecto a $\mu$ y establecemos la condición de primer orden igual a cero. Con esto, tenemos $\partial L(\mu)/\partial \mu=\sum_{i=1}^{n}(-1+y_i/\mu)=0$, 
es decir, $\hat\mu=\bar y$.

**12.3** a. De la expresión de la ecuación del score (12.5),
$$
\left. \frac{\partial }{\partial \boldsymbol \beta} L(\boldsymbol
\beta )\right\vert _{\mathbf{\beta =b}}= \sum_{i=1}^{n}\left(
y_i-\widehat{\mu }_i\right) \left(
                                                   \begin{array}{c}
                                                     1 \\ 
                                                     x_{i,1} \\ 
                                                     \vdots \\ 
                                                      x_{i,k} \\ 
                                                   \end{array}
                                                 \right) =
                                                 \mathbf{0}.
$$
De la primera fila, tenemos que el promedio de los residuales $e_i = y_i - \widehat{\mu}_i$ es igual a cero.<br>
b. De la fila $(j+1)^{st}$ de la ecuación del score (12.5), tenemos
$$
\sum_{i=1}^{n} e_i x_{i,j}= 0.
$$
Debido a que los residuales tienen un promedio igual a cero, la covarianza muestral entre los residuales y $x_j$ es cero, y por lo tanto, la correlación muestral es cero.

**12.5** a. La distribución de COUNTOP tiene una cola larga y está sesgada hacia la derecha. La varianza ($12.5^2 = 156.25$) es mucho mayor que la media, 5.67.<br>
$$
\small{
\begin{array}{cccccc} \hline
   &1st &  &  &3rd  &  \\ 
  \text{Minimum} & \text{Quartile} & \text{Median} &   \text{Mean} &\text{Quartile} &  \text{Maximum}\\\hline
   0.00   & 0.00 &   2.00 &   5.67 &   6.00 & 167.00\\ 
\hline
\end{array}
}
$$


b. Sí, las tablas sugieren que la mayoría de las variables tienen un impacto significativo en COUNTOP. <br>
c. La estadística chi-cuadrado de Pearson es 55044. <br>
d(i). Todas las variables parecen ser muy significativas estadísticamente. <br>
d(ii). El coeficiente de GENDER es 0.4197. Aproximadamente, esperaríamos que las mujeres tengan un 42\% más de gastos ambulatorios que los hombres. <br>
d(iii). La estadística chi-cuadrado es 33,214 - más baja que la parte (b) (55,044). Esto indica que las covariables ayudan en el proceso de ajuste. La significancia estadística también indica que las covariables son estadísticamente significativas, pero la sobredispersión es sospechosa - ver d(iv). <br>
d(iv). Ahora, la mayoría de las variables siguen siendo estadísticamente significativas, pero la fuerza de la significancia estadística ha disminuido dramáticamente. No está claro si la variable income es estadísticamente significativa. <br>
e(i). Todas las variables parecen ser estadísticamente significativas. La variable income es quizás la menos importante. <br>
e(ii). La estadística chi-cuadrado es 33,660 - más alta que el modelo Poisson (33,214) pero más baja que la parte (b) (55,044). Esto sugiere que los dos modelos se ajustan de manera similar, con el modelo Poisson teniendo una ligera ventaja. El AIC para el Poisson básico es 22,725 - lo cual es mucho más alto que el AIC para el binomial negativo (10,002). Por lo tanto, el binomial negativo es preferido al Poisson básico. Sin embargo, el quasi-Poisson probablemente sea tan bueno como el binomial negativo. <br>
e(iii). Según el output, la estadística de la prueba de razón de verosimilitud es 18.7 - basada en 4 grados de libertad, el $p$-valor es 0.000915. Esto indica que income es un factor estadísticamente significativo en el modelo. <br>
f. Para GENDER, educación, estado de salud personal, anylimit, income e insurance, los modelos reportan el mismo signo y efectos estadísticamente significativos. RACE no parece ser estadísticamente significativo en el modelo de regresión logística. Para REGION, los signos parecen ser los mismos aunque la significancia estadística ha cambiado.




