book_filename: "RegressionMarkdown"
# For English, comment out language files below...
#              change index file
#              Github ref in _output.yml...
#output_dir: "docsEnglish"
output_dir: "ActuarialRegression"
rmd_files: ["index.Rmd",
           "References/Packages.Rmd",
           "Chapters/Preface.Rmd",
           "Chapters/Chapter1/Chap1.Rmd",
           "Chapters/Chapter2/Chap2_Basics.Rmd",
            "Chapters/Chapter3/Chap3MLR.Rmd",
            "Chapters/Chapter4/Chap4_ANOVA.Rmd",
            "Chapters/Chapter5/Chap5VarSelection.Rmd",
            "Chapters/Chapter6/Chap6Interpretation.Rmd",
            "Chapters/Chapter7Trend/Chap7_BasicTSDec2024.Rmd",
             "Chapters/Chapter8AutoReg/Chap8_AutoRegr.Rmd",
            "Chapters/Chapter9Forecasting/Chap9_Forecasting2024.Rmd",
             "Chapters/Chapter10LongData/Chap10LongPanel2024.Rmd",
            "Chapters/Chapter11/Chap11Binary.Rmd",
             "Chapters/Chapter12/Chap12Count.Rmd",
             "Chapters/Chapter13/Chap13_GLM.Rmd",
             "Chapters/Chapter14Survival/Chap14_Survival2024.Rmd",
             "Chapters/Chapter15MiscTopics/Chap15_MiscTopics2024.Rmd",
             "Chapters/Chapter16/Chap16TwoPart.Rmd",
             "Chapters/Chapter17FatTail/Chap17_FatTail2024.Rmd",
             "Chapters/Chapter18CredibilityBM/Chap18_CredBM2024.Rmd",
             "Chapters/Chapter19Triangles/Chap19_Triangles2024.Rmd",
             "Chapters/Chapter20ReportWriting/Chap20_RptWriting2024.Rmd",
             "Chapters/Chapter21Graphs/GraphsArticle2024.Rmd",
             "Chapters/Appendices/Appendix.Rmd",
             "Chapters/Appendices/AnswersDec2024.Rmd"]
#output_dir: "docs"
# output_dir: "docsTemp"
# rmd_files: ["index.Rmd",
#             "References/Packages.Rmd",
#             "Chapters/PrefaceSpanish.Rmd",
#             "Chapters/Translation.Rmd",
#             "Chapters/Chapter1/Chap1Spanish.Rmd",
#            "Chapters/Chapter2/Chap2_BasicsSpanish.Rmd",
#              "Chapters/Chapter3/Chap3MLRSpanish.Rmd",    
            # "Chapters/Chapter4/Chap4_ANOVASpanish.Rmd",
            # "Chapters/Chapter5/Chap5VarSelectionSpanish.Rmd",   
            # "Chapters/Chapter6/Chap6InterpretationSpanish.Rmd", 
            # "Chapters/Chapter7Trend/Chap7_BasicTSSpanish.Rmd",
            # "Chapters/Chapter8AutoReg/Chap8_ARSpanish.Rmd",   
            # "Chapters/Chapter9Forecasting/Chap9_ForeSpanish.Rmd",
            # "Chapters/Chapter10LongData/Chap10LongSpanish.Rmd",
            # "Chapters/Chapter11/Chap11BinarySpanish.Rmd", 
            # "Chapters/Chapter12/Chap12CountSpanish.Rmd",  
            # "Chapters/Chapter13/Chap13_GLMSpanish.Rmd",   
            # "Chapters/Chapter14Survival/Chap14_SurvSpanish.Rmd",
            # "Chapters/Chapter15MiscTopics/Chap15_MiscSpanish.Rmd",
            # "Chapters/Chapter16/Chap16TwoPartSpanish.Rmd",
            # "Chapters/Chapter17FatTail/Chap17_FatTailSpanish.Rmd",
            # "Chapters/Chapter18CredibilityBM/Chap18_CredBMSpanish.Rmd",
            # "Chapters/Chapter19Triangles/Chap19_TrianglesSpanish.Rmd",
            # "Chapters/Chapter20ReportWriting/Chap20_RptWritingSpanish.Rmd",
            # "Chapters/Chapter21Graphs/GraphsArticleSpanish.Rmd",   
            # "Chapters/Appendices/AppendixSpanish.Rmd", 
#            "Chapters/Appendices/AnswersSpanish.Rmd"]   
delete_merged_file: TRUE #FALSE
# #tinytex::install_tinytex()
language:
  # label:
  #   fig: 'Figura '
  #   tab: 'Tabla '
  ui:
    chapter_name: "Chapter "
#    chapter_name: "Capítulo "

