--- 
title: "Regression Modeling with Actuarial and Financial Applications"
author: Edward (Jed) Frees,  University of Wisconsin - Madison, Australian National University
Affiliation:
  orcid: 0000-0001-9605-9776
site: bookdown::bookdown_site
output:
  bookdown::gitbook
documentclass: krantz
classoption: krantz2
colorlinks: yes
fontsize: 12pt
bibliography: ["References/DependRetention2024.bib"]
biblio-style: econPeriod
link-citations: yes
description: "Development of a research monograph that provides quantitative tools to assess the relevance of dependence in insurance risk management."
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment=NA, message = FALSE, warning = FALSE, fig.align="center", out.width='100%', fig.asp=0.60, results = 'asis')
HtmlEval <- knitr:::is_html_output()
PdfEval  <- knitr:::is_latex_output()
# This set is for Online Supplements
Ch1PdfEval  <- FALSE -> Ch2PdfEval -> Ch3PdfEval -> Ch4PdfEval -> Ch5PdfEval -> Ch6PdfEval -> Ch7PdfEval
Ch8PdfEval  <- FALSE -> Ch9PdfEval -> Ch10PdfEval -> Ch11PdfEval -> Ch12PdfEval -> Ch13PdfEval
#  This set is for cross-referencing
TRUE -> Ch1Eval -> Ch2Eval 
TRUE -> Ch3Eval  
TRUE -> Ch4Eval -> Ch5Eval -> Ch6Eval ->   Ch7Eval -> Ch8Eval
TRUE -> Ch11Eval 
TRUE -> Ch9Eval   -> Ch10Eval
TRUE -> Ch13Eval 
TRUE -> Ch12Eval -> Ch14Eval

NOTCAMPUS <- FALSE # For Cache, Dropbox, Not used anymore
if (HtmlEval) { 
  FigRed    = "red"        ;  FigBlue   = "blue"
  FigGreen  = "green"      ;  FigLBlue  = "lightblue"
  FigDBlue  = "darkblue"   ;  FigDGreen = "darkgreen"
  FigLGreen = "lightgreen" ;  FigOrange = "orange"      
  } else { 
  FigRed    = "black"      ;  FigBlue   = "black"
  FigGreen  = "black"      ;  FigLBlue  = "gray"
  FigDBlue  = "black"      ;  FigDGreen = "gray"  
  FigLGreen = "gray"       ;  FigOrange = "black"        
  }

printHtml <- function(A, B=""){if (HtmlEval) { A } else { B }}

CrossRefEval <- FALSE
printCrossRef<- function(A, B=""){if (CrossRefEval) { A } else { B }}
ChapCrossRef<- function(ChapEval, A, B=""){if (ChapEval) { A } else { B }}

PdfNote.fct <- function(A){ if(PdfEval==TRUE){knitr::asis_output(paste("*Note.*", A))}}



```


```{r child = './References/Packages.Rmd', include = FALSE}
```

```{r child = './References/CommonFunctions.Rmd', include = FALSE}
```

```{r child = './References/HideShowCode.Rmd', include = FALSE}
```


<!-- \mainmatter -->

# It Takes a Team {-}


```{r echo = FALSE}
timeDraft <- Sys.time()
```

