

# It Takes a Team {-}

***
<font color="blue" size="+2">**Under Construction**!!!</font> 


<br>

**What?** The purpose of this project is to develop a Spanish translation for the text *Regression Modeling with Actuarial and Financial Application.* This translation will be open and freely available - a resource for our community. 

**Why?** Regression provides the foundations for data science techniques such as machine learning. Although this book is a bit dated (written in 2009), it provides an easy introduction to statistical learning tools geared for applications of interest to actuaries and other financial analysts.

**Who?** We need your help!

* Jed Frees <jfrees@bus.wisc.edu> is the author of the text and has secured permission from Cambridge University Press to publish an online Spanish version. Jed is learning Spanish and is familiar with online publishing. He will take responsibility for uploading the translated version to the web.
* Armando Zarruk Rivera <azarrukr@unal.edu.co> has experience translating general insurance data analytics texts. He will coordinate translation volunteers.

We need translation volunteers! Read more below - if this appeals to you, contact Armando and Jed to express your interest in helping.

**How?** We will follow a procedure similar to our successful Spanish version of *Loss Data Analytics*, available at https://openacttexts.github.io/LDASpanish/.
Check out our [Google Usage Data](https://openacttextdev.github.io/LDA_Ed2/GoogleAnalyticsUsage2023.html) to see who is using this book.

In short, Jed will convert his text, written in 2009 using latex, to R markdown and then put it on [Github](https://github.com/OpenActTextDev/RegressionSpanish). Each chapter takes many days to do -- you can see the Preface and first chapter on the Github site. Translators may then download these text files, translate them, and then send back to Jed who will take care of uploading them to Github. 

*Armando, probably need better instructions here but this is a start....*

For example, you might start with an AI assistance tool. We like the idea of using machines to facilitate our work but ultimately need humans to assess the quality of the final product. Click on the following link to reveal a translation of the first two paragraphs of the Preface using the free tool, ChatGPT. Check it out!


<p style="text-align:right;">
*Date: `r format(Sys.Date(), "%d %B %Y")`*</p>

