


# Traducción {-}

<font color="blue" size="+2">**Under Construction**!!!</font> 

<br>

**What?** The purpose of this project is to develop a Spanish translation for the text *Regression Modeling with Actuarial and Financial Application.* This translation will be open and freely available - a resource for our community. 

**Why?** Regression provides the foundations for data science techniques such as machine learning. Although this book is a bit dated (written in 2009), it provides an easy introduction to statistical learning tools geared for applications of interest to actuaries and other financial analysts.

**Who?** 

* Jed Frees <jfrees@bus.wisc.edu> is the author of the text and has secured permission from Cambridge University Press to publish an online Spanish version. Jed is learning Spanish and is familiar with online publishing. He will take responsibility for uploading the translated version to the web.
* Carla Parodi and Armando Zarruk (Chair) of the Society of Actuaries´s Latin America Committee will be coordinating translation volunteers. It has been already confirmed the collaboration from the different Associations of Actuaries of Latam countries, including those from Argentina, Colombia, Ecuador, Mexico, Panama, and Peru. If you are interested in participating, please contact carla.parodi@carlaparodi.com and/or azarrukr@unal.edu.co .


**How?** We are following a procedure similar to our successful Spanish version of *Loss Data Analytics*, available at https://openacttexts.github.io/LDASpanish/.
Check out our [Google Usage Data](https://openacttextdev.github.io/LDA_Ed2/GoogleAnalyticsUsage2023.html) to see who is using this book.

In short, Jed has converted his text, written in 2009 using latex, to R markdown. He then used ChatGPT for the initial translation into Spanish. Volunteers will review this translation.


*  If the number of suggested changes are small, probably these easiest thing is to send them Carla and Armando. They will review for consistency among terminology, then forward on to Jed who will upload the changes to Github. 
*  If major changes are required, another possibility is to go to the [Github](https://github.com/OpenActTextDev/RegressionSpanish) site, download the .Rmd file, make the changes in the file, and send on to Jed. 

An ".Rmd" file is based on R's version of a markdown file. You can open it with any text editor (e.g. Notepad - not Word), make changes, and save as text file.


<p style="text-align:right;">
*Date: `r format(Sys.Date(), "%d %B %Y")`*</p>

***



